name: all

on: workflow_dispatch

jobs:
  VPS0:
    runs-on: windows-latest
    timeout-minutes: 9999

    steps:
    - name: Download Ngrok
      run: |
        Invoke-WebRequest https://github.com/blueroler/RDP_main/blob/main/ngrok.zip?raw=true -OutFile ngrok.zip
        Invoke-WebRequest https://raw.githubusercontent.com/blueroler/RDP_main/main/start.bat -OutFile start.bat
        Invoke-WebRequest https://raw.githubusercontent.com/blueroler/RDP_main/main/loop.bat -OutFile loop.bat
    - name: Extracting Ngrok Files
      run: Expand-Archive ngrok.zip
    - name: Connect To Ngrok Account
      run: .\ngrok\ngrok.exe authtoken $Env:CHIEN
      env:
        CHIEN: ${{ secrets.CHIEN }}
    - name: Enable RDP Access
      run: | 
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
    - name: Create Tunnels
      run: Start-Process Powershell -ArgumentList '-Noexit -Command ".\ngrok\ngrok.exe tcp --region ap 3389"'
    - name: Connect to your RDP
      run: cmd /c start.bat
    - name: Made Successfully! You Can Close Tab Now
      run: cmd /c loop.bat

  VPS1:
    runs-on: windows-latest
    timeout-minutes: 9999

    steps:
    - name: Download Ngrok
      run: |
        Invoke-WebRequest https://github.com/blueroler/RDP_main/blob/main/ngrok.zip?raw=true -OutFile ngrok.zip
        Invoke-WebRequest https://raw.githubusercontent.com/blueroler/RDP_main/main/start.bat -OutFile start.bat
        Invoke-WebRequest https://raw.githubusercontent.com/blueroler/RDP_main/main/loop.bat -OutFile loop.bat
    - name: Extracting Ngrok Files
      run: Expand-Archive ngrok.zip
    - name: Connect To Ngrok Account
      run: .\ngrok\ngrok.exe authtoken $Env:FUCK
      env:
        FUCK: ${{ secrets.FUCK }}
    - name: Enable RDP Access
      run: | 
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
    - name: Create Tunnels
      run: Start-Process Powershell -ArgumentList '-Noexit -Command ".\ngrok\ngrok.exe tcp --region ap 3389"'
    - name: Connect to your RDP
      run: cmd /c start.bat
    - name: Made Successfully! You Can Close Tab Now
      run: cmd /c loop.bat

  VPS2:
    runs-on: windows-latest
    timeout-minutes: 9999

    steps:
    - name: Download Ngrok
      run: |
        Invoke-WebRequest https://github.com/blueroler/RDP_main/blob/main/ngrok.zip?raw=true -OutFile ngrok.zip
        Invoke-WebRequest https://raw.githubusercontent.com/blueroler/RDP_main/main/start.bat -OutFile start.bat
        Invoke-WebRequest https://raw.githubusercontent.com/blueroler/RDP_main/main/loop.bat -OutFile loop.bat
    - name: Extracting Ngrok Files
      run: Expand-Archive ngrok.zip
    - name: Connect To Ngrok Account
      run: .\ngrok\ngrok.exe authtoken $Env:HUNG
      env:
        HUNG: ${{ secrets.HUNG }}
    - name: Enable RDP Access
      run: | 
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
    - name: Create Tunnels
      run: Start-Process Powershell -ArgumentList '-Noexit -Command ".\ngrok\ngrok.exe tcp --region ap 3389"'
    - name: Connect to your RDP
      run: cmd /c start.bat
    - name: Made Successfully! You Can Close Tab Now
      run: cmd /c loop.bat

  VPS3:
    runs-on: windows-latest
    timeout-minutes: 9999

    steps:
    - name: Download Ngrok
      run: |
        Invoke-WebRequest https://github.com/blueroler/RDP_main/blob/main/ngrok.zip?raw=true -OutFile ngrok.zip
        Invoke-WebRequest https://raw.githubusercontent.com/blueroler/RDP_main/main/start.bat -OutFile start.bat
        Invoke-WebRequest https://raw.githubusercontent.com/blueroler/RDP_main/main/loop.bat -OutFile loop.bat
    - name: Extracting Ngrok Files
      run: Expand-Archive ngrok.zip
    - name: Connect To Ngrok Account
      run: .\ngrok\ngrok.exe authtoken $Env:MANH
      env:
        MANH: ${{ secrets.MANH }}
    - name: Enable RDP Access
      run: | 
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
    - name: Create Tunnels
      run: Start-Process Powershell -ArgumentList '-Noexit -Command ".\ngrok\ngrok.exe tcp --region ap 3389"'
    - name: Connect to your RDP
      run: cmd /c start.bat
    - name: Made Successfully! You Can Close Tab Now
      run: cmd /c loop.bat

  VPS4:
    runs-on: windows-latest
    timeout-minutes: 9999

    steps:
    - name: Download Ngrok
      run: |
        Invoke-WebRequest https://github.com/blueroler/RDP_main/blob/main/ngrok.zip?raw=true -OutFile ngrok.zip
        Invoke-WebRequest https://raw.githubusercontent.com/blueroler/RDP_main/main/start.bat -OutFile start.bat
        Invoke-WebRequest https://raw.githubusercontent.com/blueroler/RDP_main/main/loop.bat -OutFile loop.bat
    - name: Extracting Ngrok Files
      run: Expand-Archive ngrok.zip
    - name: Connect To Ngrok Account
      run: .\ngrok\ngrok.exe authtoken $Env:NGAN
      env:
        NGAN: ${{ secrets.NGAN }}
    - name: Enable RDP Access
      run: | 
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
    - name: Create Tunnels
      run: Start-Process Powershell -ArgumentList '-Noexit -Command ".\ngrok\ngrok.exe tcp --region ap 3389"'
    - name: Connect to your RDP
      run: cmd /c start.bat
    - name: Made Successfully! You Can Close Tab Now
      run: cmd /c loop.bat

  VPS5:
    runs-on: windows-latest
    timeout-minutes: 9999

    steps:
    - name: Download Ngrok
      run: |
        Invoke-WebRequest https://github.com/blueroler/RDP_main/blob/main/ngrok.zip?raw=true -OutFile ngrok.zip
        Invoke-WebRequest https://raw.githubusercontent.com/blueroler/RDP_main/main/start.bat -OutFile start.bat
        Invoke-WebRequest https://raw.githubusercontent.com/blueroler/RDP_main/main/loop.bat -OutFile loop.bat
    - name: Extracting Ngrok Files
      run: Expand-Archive ngrok.zip
    - name: Connect To Ngrok Account
      run: .\ngrok\ngrok.exe authtoken $Env:NHUT
      env:
        NHUT: ${{ secrets.NHUT }}
    - name: Enable RDP Access
      run: | 
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
    - name: Create Tunnels
      run: Start-Process Powershell -ArgumentList '-Noexit -Command ".\ngrok\ngrok.exe tcp --region ap 3389"'
    - name: Connect to your RDP
      run: cmd /c start.bat
    - name: Made Successfully! You Can Close Tab Now
      run: cmd /c loop.bat

  VPS6:
    runs-on: windows-latest
    timeout-minutes: 9999

    steps:
    - name: Download Ngrok
      run: |
        Invoke-WebRequest https://github.com/blueroler/RDP_main/blob/main/ngrok.zip?raw=true -OutFile ngrok.zip
        Invoke-WebRequest https://raw.githubusercontent.com/blueroler/RDP_main/main/start.bat -OutFile start.bat
        Invoke-WebRequest https://raw.githubusercontent.com/blueroler/RDP_main/main/loop.bat -OutFile loop.bat
    - name: Extracting Ngrok Files
      run: Expand-Archive ngrok.zip
    - name: Connect To Ngrok Account
      run: .\ngrok\ngrok.exe authtoken $Env:QUYEN
      env:
        QUYEN: ${{ secrets.QUYEN }}
    - name: Enable RDP Access
      run: | 
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
    - name: Create Tunnels
      run: Start-Process Powershell -ArgumentList '-Noexit -Command ".\ngrok\ngrok.exe tcp --region ap 3389"'
    - name: Connect to your RDP
      run: cmd /c start.bat
    - name: Made Successfully! You Can Close Tab Now
      run: cmd /c loop.bat

  VPS7:
    runs-on: windows-latest
    timeout-minutes: 9999

    steps:
    - name: Download Ngrok
      run: |
        Invoke-WebRequest https://github.com/blueroler/RDP_main/blob/main/ngrok.zip?raw=true -OutFile ngrok.zip
        Invoke-WebRequest https://raw.githubusercontent.com/blueroler/RDP_main/main/start.bat -OutFile start.bat
        Invoke-WebRequest https://raw.githubusercontent.com/blueroler/RDP_main/main/loop.bat -OutFile loop.bat
    - name: Extracting Ngrok Files
      run: Expand-Archive ngrok.zip
    - name: Connect To Ngrok Account
      run: .\ngrok\ngrok.exe authtoken $Env:SY
      env:
        SY: ${{ secrets.SY }}
    - name: Enable RDP Access
      run: | 
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
    - name: Create Tunnels
      run: Start-Process Powershell -ArgumentList '-Noexit -Command ".\ngrok\ngrok.exe tcp --region ap 3389"'
    - name: Connect to your RDP
      run: cmd /c start.bat
    - name: Made Successfully! You Can Close Tab Now
      run: cmd /c loop.bat

  VPS8:
    runs-on: windows-latest
    timeout-minutes: 9999

    steps:
    - name: Download Ngrok
      run: |
        Invoke-WebRequest https://github.com/blueroler/RDP_main/blob/main/ngrok.zip?raw=true -OutFile ngrok.zip
        Invoke-WebRequest https://raw.githubusercontent.com/blueroler/RDP_main/main/start.bat -OutFile start.bat
        Invoke-WebRequest https://raw.githubusercontent.com/blueroler/RDP_main/main/loop.bat -OutFile loop.bat
    - name: Extracting Ngrok Files
      run: Expand-Archive ngrok.zip
    - name: Connect To Ngrok Account
      run: .\ngrok\ngrok.exe authtoken $Env:THU
      env:
        THU: ${{ secrets.THU }}
    - name: Enable RDP Access
      run: | 
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
    - name: Create Tunnels
      run: Start-Process Powershell -ArgumentList '-Noexit -Command ".\ngrok\ngrok.exe tcp --region ap 3389"'
    - name: Connect to your RDP
      run: cmd /c start.bat
    - name: Made Successfully! You Can Close Tab Now
      run: cmd /c loop.bat

  VPS9:
    runs-on: windows-latest
    timeout-minutes: 9999

    steps:
    - name: Download Ngrok
      run: |
        Invoke-WebRequest https://github.com/blueroler/RDP_main/blob/main/ngrok.zip?raw=true -OutFile ngrok.zip
        Invoke-WebRequest https://raw.githubusercontent.com/blueroler/RDP_main/main/start.bat -OutFile start.bat
        Invoke-WebRequest https://raw.githubusercontent.com/blueroler/RDP_main/main/loop.bat -OutFile loop.bat
    - name: Extracting Ngrok Files
      run: Expand-Archive ngrok.zip
    - name: Connect To Ngrok Account
      run: .\ngrok\ngrok.exe authtoken $Env:THUY
      env:
        THUY: ${{ secrets.THUY }}
    - name: Enable RDP Access
      run: | 
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
    - name: Create Tunnels
      run: Start-Process Powershell -ArgumentList '-Noexit -Command ".\ngrok\ngrok.exe tcp --region ap 3389"'
    - name: Connect to your RDP
      run: cmd /c start.bat
    - name: Made Successfully! You Can Close Tab Now
      run: cmd /c loop.bat