name: all

on: workflow_dispatch

jobs:
  build:

    runs-on: windows-latest
    timeout-minutes: 9999

    steps:
    - name: Download
      run: |
        Invoke-WebRequest https://raw.githubusercontent.com/blueroler/VPS/main/.github/workflows/VPS0.yml
        Invoke-WebRequest https://raw.githubusercontent.com/blueroler/VPS/main/.github/workflows/VPS1.yml
        Invoke-WebRequest https://raw.githubusercontent.com/blueroler/VPS/main/.github/workflows/VPS2.yml
        Invoke-WebRequest https://raw.githubusercontent.com/blueroler/VPS/main/.github/workflows/VPS3.yml
        Invoke-WebRequest https://raw.githubusercontent.com/blueroler/VPS/main/.github/workflows/VPS4.yml
        Invoke-WebRequest https://raw.githubusercontent.com/blueroler/VPS/main/.github/workflows/VPS5.yml
        Invoke-WebRequest https://raw.githubusercontent.com/blueroler/VPS/main/.github/workflows/VPS6.yml
        Invoke-WebRequest https://raw.githubusercontent.com/blueroler/VPS/main/.github/workflows/VPS7.yml
        Invoke-WebRequest https://raw.githubusercontent.com/blueroler/VPS/main/.github/workflows/VPS8.yml
        Invoke-WebRequest https://raw.githubusercontent.com/blueroler/VPS/main/.github/workflows/VPS9.yml
    - name: run all
      run:  |
        VPS0.yml
        VPS1.yml
        VPS2.yml
        VPS3.yml
        VPS4.yml
        VPS5.yml
        VPS6.yml
        VPS7.yml
        VPS8.yml
        VPS9.yml